---
driver:
  name: vagrant
  username: root
  password: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
  synced_folders:
    - ["./chef-installer", "/tmp/chef-installer"]

provisioner:
  name: chef_zero
  chef_omnibus_url: file:///tmp/chef-installer/install.sh

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[tomcat::default]
